pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stages {
    stage('Dev') {
      steps {
        sh 'java -version'
      }
    }
      stages {
    stage('prod') {
      steps {
        sh 'jenkins --version'
      }
    }
        stages {
    stage('stage') {
      steps {
        sh 'docker --version'
      }
    }
          stages {
    stage('deploy') {
      steps {
        sh 'ps -ef | grep jenkins'
      }
    }
  }
}
}
